import React, { useState, useEffect } from 'react';
import { db } from '../../lib/firebase';
import { collection, onSnapshot } from 'firebase/firestore';
import { MemberCardModal } from '../MemberCardModal';
import {
  Users,
  User,
  Search,
  GraduationCap,
  Calendar,
  Phone,
  Mail,
  MapPin,
  Eye,
  X,
  UserPlus,
  RefreshCw,
  Award,
  CheckCircle2,
  Building2,
  BookOpen,
  ArrowLeft,
  Sparkles,
  LayoutGrid,
  List,
  FileText,
  Hash,
  Home,
  ChevronLeft,
  ChevronRight,
  Download,
  Share2
} from 'lucide-react';

export interface MemberRecord {
  id: string;
  formNo?: string;
  applicantNameBn: string;
  applicantNameEn?: string;
  program?: string;
  academicYear?: string;
  session?: string;
  classRoll?: string;
  regNumber?: string;
  mobile?: string;
  email?: string;
  bloodGroup?: string;
  district?: string;
  village?: string;
  currentAddress?: string;
  paymentMethod?: string;
  transactionId?: string;
  date?: string;
  userPhotoUrl?: string;
  status?: string;
}

// Convert Bengali digits (০-৯) to English digits (0-9)
const bnToEnDigits = (str: string): string => {
  const banglaDigits = ['০', '১', '২', '৩', '৪', '৫', '৬', '৭', '৮', '৯'];
  return str.replace(/[০-৯]/g, (d) => String(banglaDigits.indexOf(d)));
};

// Card theme color styles for vibrant aesthetic cards
const CARD_THEMES = [
  {
    bg: 'bg-gradient-to-br from-emerald-50/95 via-teal-50/70 to-emerald-100/60',
    border: 'border-emerald-300 hover:border-emerald-500',
    ribbonBg: 'bg-emerald-700 text-white',
    avatarBg: 'bg-emerald-600 text-white shadow-emerald-200',
    btnBg: 'bg-gradient-to-r from-emerald-700 to-teal-800 hover:from-emerald-800 hover:to-teal-900',
    accentText: 'text-emerald-800',
    infoBox: 'bg-white/85 border-emerald-200/90 shadow-2xs',
  },
  {
    bg: 'bg-gradient-to-br from-amber-50/95 via-orange-50/70 to-amber-100/60',
    border: 'border-amber-300 hover:border-amber-500',
    ribbonBg: 'bg-amber-700 text-white',
    avatarBg: 'bg-amber-600 text-white shadow-amber-200',
    btnBg: 'bg-gradient-to-r from-amber-700 to-orange-800 hover:from-amber-800 hover:to-orange-900',
    accentText: 'text-amber-900',
    infoBox: 'bg-white/85 border-amber-200/90 shadow-2xs',
  },
  {
    bg: 'bg-gradient-to-br from-sky-50/95 via-cyan-50/70 to-blue-100/60',
    border: 'border-sky-300 hover:border-sky-500',
    ribbonBg: 'bg-sky-800 text-white',
    avatarBg: 'bg-sky-700 text-white shadow-sky-200',
    btnBg: 'bg-gradient-to-r from-sky-800 to-blue-900 hover:from-sky-900 hover:to-blue-950',
    accentText: 'text-sky-900',
    infoBox: 'bg-white/85 border-sky-200/90 shadow-2xs',
  },
  {
    bg: 'bg-gradient-to-br from-indigo-50/95 via-purple-50/70 to-indigo-100/60',
    border: 'border-indigo-300 hover:border-indigo-500',
    ribbonBg: 'bg-indigo-800 text-white',
    avatarBg: 'bg-indigo-700 text-white shadow-indigo-200',
    btnBg: 'bg-gradient-to-r from-indigo-800 to-purple-900 hover:from-indigo-900 hover:to-purple-950',
    accentText: 'text-indigo-900',
    infoBox: 'bg-white/85 border-indigo-200/90 shadow-2xs',
  }
];

interface MembersListPageProps {
  language: 'bn' | 'en';
  onNavigateToRegister?: () => void;
  onBackToHome?: () => void;
}

const ITEMS_PER_PAGE = 9;

export const MembersListPage: React.FC<MembersListPageProps> = ({
  language,
  onNavigateToRegister,
  onBackToHome,
}) => {
  const [members, setMembers] = useState<MemberRecord[]>([]);
  const [loading, setLoading] = useState<boolean>(true);
  const [searchQuery, setSearchQuery] = useState<string>('');
  const [programFilter, setProgramFilter] = useState<string>('all');
  const [sessionFilter, setSessionFilter] = useState<string>('all');
  const [selectedMember, setSelectedMember] = useState<MemberRecord | null>(null);
  const [viewMode, setViewMode] = useState<'grid' | 'table'>('grid');
  const [currentPage, setCurrentPage] = useState<number>(1);

  // Real-time listener for Firestore memberships collection
  // When an admin deletes a member from the admin dashboard, Firestore onSnapshot immediately updates this list
  useEffect(() => {
    let unsubscribe = () => {};
    try {
      const q = collection(db, 'memberships');
      unsubscribe = onSnapshot(
        q,
        (snapshot) => {
          if (!snapshot.empty) {
            const dbList: MemberRecord[] = [];
            snapshot.forEach((docSnap) => {
              const data = docSnap.data() as any;
              // Include registered/approved members (exclude only if explicitly rejected)
              if (data.status !== 'rejected') {
                const autoGeneratedFormNo = `BOT-ALUMNI-${(Math.abs(docSnap.id.split('').reduce((a, b) => (((a << 5) - a) + b.charCodeAt(0)) | 0, 0)) % 9000 + 1000)}`;
                dbList.push({
                  id: docSnap.id,
                  formNo: data.formNo || autoGeneratedFormNo,
                  applicantNameBn: data.applicantNameBn || data.fullName || 'নামহীন সদস্য',
                  applicantNameEn: data.applicantNameEn || '',
                  program: data.program || 'bsc_honours',
                  academicYear: data.academicYear || '',
                  session: data.session || data.batch || '',
                  classRoll: data.classRoll || '',
                  regNumber: data.regNumber || '',
                  mobile: data.mobile || '',
                  email: data.email || '',
                  bloodGroup: data.bloodGroup || '',
                  district: data.district || '',
                  village: data.village || '',
                  currentAddress: data.currentAddress || data.presentAddress || '',
                  paymentMethod: data.paymentMethod || 'Manual',
                  transactionId: data.transactionId || '',
                  date: data.date || (data.createdAt ? new Date(data.createdAt).toLocaleDateString('bn-BD') : ''),
                  userPhotoUrl: data.userPhotoUrl || '',
                  status: data.status || 'approved',
                });
              }
            });

            // Sort by formNo or registration date
            dbList.sort((a, b) => (b.formNo || '').localeCompare(a.formNo || ''));
            setMembers(dbList);
          } else {
            setMembers([]);
          }
          setLoading(false);
        },
        (error) => {
          console.warn('Firestore real-time load notice:', error);
          setLoading(false);
        }
      );
    } catch (e) {
      console.warn('Firestore subscription error:', e);
      setLoading(false);
    }

    return () => unsubscribe();
  }, []);

  // Reset to page 1 whenever filters or search query change
  useEffect(() => {
    setCurrentPage(1);
  }, [searchQuery, programFilter, sessionFilter]);

  // Filter list: Search strictly by Registration Form Number / Last 4 Digits only
  const filteredMembers = members.filter((m) => {
    const rawQuery = searchQuery.trim();
    if (!rawQuery) {
      const matchesProgram = programFilter === 'all' || m.program === programFilter;
      const matchesSession = sessionFilter === 'all' || m.session === sessionFilter;
      return matchesProgram && matchesSession;
    }

    // Convert query (Bengali/English digits & alphanumeric)
    const qEn = bnToEnDigits(rawQuery).toLowerCase().replace(/[^a-z0-9]/gi, '');
    const memberFormNo = (m.formNo || m.id || '').toLowerCase();
    const memberFormNoClean = bnToEnDigits(memberFormNo).replace(/[^a-z0-9]/gi, '');

    // Extract last 4 digits if present (e.g. 4655 from SOC-ALUMNI-4655)
    const digitsOnly = memberFormNoClean.replace(/\D/g, '');
    const last4Digits = digitsOnly.slice(-4);

    // Only matches registration form number or its last 4 digits
    const matchesSearch =
      memberFormNoClean.includes(qEn) ||
      last4Digits.includes(qEn) ||
      digitsOnly.includes(qEn) ||
      memberFormNo.includes(rawQuery.toLowerCase());

    const matchesProgram =
      programFilter === 'all' || m.program === programFilter;

    const matchesSession =
      sessionFilter === 'all' || m.session === sessionFilter;

    return matchesSearch && matchesProgram && matchesSession;
  });

  // Pagination calculation: max 9 members per page
  const totalMembersCount = filteredMembers.length;
  const totalPages = Math.max(1, Math.ceil(totalMembersCount / ITEMS_PER_PAGE));
  const startIndex = (currentPage - 1) * ITEMS_PER_PAGE;
  const endIndex = Math.min(startIndex + ITEMS_PER_PAGE, totalMembersCount);
  const paginatedMembers = filteredMembers.slice(startIndex, startIndex + ITEMS_PER_PAGE);

  const handlePageChange = (newPage: number) => {
    if (newPage >= 1 && newPage <= totalPages) {
      setCurrentPage(newPage);
      // Smoothly scroll window and document to the top
      window.scrollTo({ top: 0, left: 0, behavior: 'smooth' });
      document.documentElement.scrollTo({ top: 0, left: 0, behavior: 'smooth' });
      document.body.scrollTo({ top: 0, left: 0, behavior: 'smooth' });
      const topEl = document.getElementById('members-list-page') || document.getElementById('root');
      if (topEl) {
        topEl.scrollIntoView({ behavior: 'smooth', block: 'start' });
      }
    }
  };

  const getProgramLabel = (prog?: string) => {
    switch (prog) {
      case 'bsc_honours':
      case 'bss_honours':
        return language === 'bn' ? 'বিএসসি (সম্মান)' : 'BSc (Honours)';
      case 'msc_masters':
      case 'mss_masters':
        return language === 'bn' ? 'এমএসসি (মাস্টার্স)' : 'MSc (Masters)';
      default:
        return language === 'bn' ? 'উদ্ভিদবিজ্ঞান' : 'Botany';
    }
  };

  // Unique sessions list for dropdown
  const sessionList = Array.from(
    new Set(members.map((m) => m.session).filter(Boolean))
  );

  return (
    <div id="members-list-page" className="w-full bg-[#f4f7f5] p-3 sm:p-6 lg:p-8 font-siliguri space-y-4 sm:space-y-6">
      
      {/* Navigation Top Bar (Back button if available) */}
      {onBackToHome && (
        <div className="flex items-center justify-between no-print">
          <button
            onClick={onBackToHome}
            className="inline-flex items-center gap-1.5 text-xs sm:text-sm font-bold text-[#006a4e] hover:text-[#00523d] transition-colors cursor-pointer py-1"
          >
            <ArrowLeft className="w-4 h-4" />
            <span>{language === 'bn' ? 'মূল পাতায় ফিরে যান' : 'Back to Home'}</span>
          </button>
        </div>
      )}

      {/* Top Banner & Header - Mobile Optimized with College Colors */}
      <div className="bg-gradient-to-br from-[#004d38] via-[#006a4e] to-[#003828] text-white rounded-2xl p-4 sm:p-6 md:p-8 shadow-lg border border-emerald-600/40 relative overflow-hidden">
        {/* Subtle Background Graphic */}
        <div className="absolute -right-8 -bottom-8 w-40 h-40 bg-white/5 rounded-full blur-2xl pointer-events-none" />
        
        <div className="flex flex-col md:flex-row items-start md:items-center justify-between gap-4 relative z-10">
          <div className="space-y-2">
            <div className="inline-flex items-center gap-2 bg-amber-400/20 text-amber-300 px-3 py-1 rounded-full text-xs font-bold border border-amber-400/30 backdrop-blur-xs">
              <Users className="w-3.5 h-3.5" />
              <span>{language === 'bn' ? 'উদ্ভিদবিজ্ঞান বিভাগীয় বাতায়ন' : 'Botany Alumni Directory'}</span>
            </div>

            <h1 className="text-lg sm:text-2xl md:text-3xl font-black tracking-tight font-serif-bn leading-tight text-white">
              {language === 'bn'
                ? 'সদস্য নিবন্ধন তালিকা'
                : 'Botany Members Directory'}
            </h1>

            <p className="text-xs sm:text-sm text-emerald-100/90 font-medium max-w-2xl leading-relaxed">
              {language === 'bn'
                ? 'রেজিস্ট্রেশন ফরম নং-এর শেষ ৪ ডিজিট দিয়ে তাৎক্ষণিকভাবে যেকোনো সদস্যের কার্ড, ব্যাচ, মোবাইল নম্বর ও ঠিকানা খুঁজুন।'
                : 'Search any registered alumni instantly by entering the last 4 digits of Registration Form No.'}
            </p>
          </div>
        </div>
      </div>

      {/* Summary KPI Stats Bar - Mobile Friendly Grid */}
      <div className="grid grid-cols-3 gap-2 sm:gap-4">
        {/* Total Members */}
        <div className="bg-white border border-emerald-200 p-2.5 sm:p-4 rounded-xl text-center space-y-0.5 shadow-xs">
          <span className="text-[10px] sm:text-xs text-gray-500 font-bold block truncate">
            {language === 'bn' ? 'মোট নিবন্ধিত' : 'Total Members'}
          </span>
          <span className="text-lg sm:text-2xl font-black text-[#006a4e]">
            {members.length}
          </span>
        </div>

        {/* BSc Honours */}
        <div className="bg-white border border-emerald-200 p-2.5 sm:p-4 rounded-xl text-center space-y-0.5 shadow-xs">
          <span className="text-[10px] sm:text-xs text-gray-500 font-bold block truncate">
            {language === 'bn' ? 'বিএসসি (সম্মান)' : 'BSc Honours'}
          </span>
          <span className="text-lg sm:text-2xl font-black text-emerald-700">
            {members.filter((m) => m.program === 'bsc_honours' || m.program === 'bss_honours').length}
          </span>
        </div>

        {/* MSc Masters */}
        <div className="bg-white border border-sky-200 p-2.5 sm:p-4 rounded-xl text-center space-y-0.5 shadow-xs">
          <span className="text-[10px] sm:text-xs text-gray-500 font-bold block truncate">
            {language === 'bn' ? 'এমএসসি (মাস্টার্স)' : 'MSc Masters'}
          </span>
          <span className="text-lg sm:text-2xl font-black text-sky-700">
            {members.filter((m) => m.program === 'msc_masters' || m.program === 'mss_masters').length}
          </span>
        </div>
      </div>

      {/* Filter & Search Box - Optimized for Registration Form No. Search */}
      <div className="bg-white border border-[#cce0d2] rounded-2xl p-3.5 sm:p-5 shadow-xs space-y-3">
        
        {/* Registration Form No. Search Input */}
        <div className="space-y-1.5">
          <div className="flex items-center">
            <label
              htmlFor="member-search-query-input"
              className="text-xs font-bold text-gray-800 flex items-center gap-1.5 whitespace-nowrap"
            >
              <FileText className="w-3.5 h-3.5 text-[#006a4e] shrink-0" />
              <span className="whitespace-nowrap">
                {language === 'bn'
                  ? 'রেজিস্ট্রেশন ফরম নং দিয়ে অনুসন্ধান:'
                  : 'Search by Registration Form No:'}
              </span>
            </label>
          </div>

          <div className="relative">
            <input
              id="member-search-query-input"
              type="text"
              placeholder={
                language === 'bn'
                  ? 'রেজিস্ট্রেশন ফরম নং-এর শেষ ৪ ডিজিট লিখুন (যেমন: 4655)...'
                  : 'Enter last 4 digits of Registration No (e.g. 4655)...'
              }
              value={searchQuery}
              onChange={(e) => setSearchQuery(e.target.value)}
              className="w-full pl-9 pr-8 py-2.5 text-xs sm:text-sm bg-gray-50/80 border-2 border-emerald-500/50 rounded-xl focus:outline-none focus:ring-2 focus:ring-[#006a4e] focus:bg-white text-gray-900 font-mono transition-all placeholder:font-sans placeholder:text-gray-400 shadow-inner"
            />
            <Search className="w-4 h-4 text-emerald-700 absolute left-3 top-1/2 -translate-y-1/2" />
            {searchQuery && (
              <button
                onClick={() => setSearchQuery('')}
                className="absolute right-2.5 top-1/2 -translate-y-1/2 text-gray-400 hover:text-gray-600 p-1 cursor-pointer"
              >
                <X className="w-4 h-4" />
              </button>
            )}
          </div>
        </div>

        {/* Filter Dropdowns Grid: Only Program & Session */}
        <div className="grid grid-cols-2 sm:grid-cols-3 gap-2 pt-0.5">
          {/* Program Filter */}
          <select
            id="member-program-filter"
            value={programFilter}
            onChange={(e) => setProgramFilter(e.target.value)}
            className="w-full bg-gray-50 border border-gray-300 text-xs font-semibold px-2.5 py-2 rounded-xl focus:outline-none focus:ring-2 focus:ring-[#006a4e] text-gray-700 cursor-pointer"
          >
            <option value="all">{language === 'bn' ? 'সকল কোর্স' : 'All Programs'}</option>
            <option value="bsc_honours">{language === 'bn' ? 'বিএসসি (সম্মান)' : 'BSc (Honours)'}</option>
            <option value="msc_masters">{language === 'bn' ? 'এমএসসি (মাস্টার্স)' : 'MSc (Masters)'}</option>
          </select>

          {/* Session Filter */}
          <select
            id="member-session-filter"
            value={sessionFilter}
            onChange={(e) => setSessionFilter(e.target.value)}
            className="w-full bg-gray-50 border border-gray-300 text-xs font-semibold px-2.5 py-2 rounded-xl focus:outline-none focus:ring-2 focus:ring-[#006a4e] text-gray-700 cursor-pointer"
          >
            <option value="all">{language === 'bn' ? 'সকল ব্যাচ/সেশন' : 'All Batches'}</option>
            {sessionList.map((ses, sIdx) => (
              <option key={sIdx} value={ses}>
                {ses}
              </option>
            ))}
          </select>

          {/* Reset Filters Button */}
          {(searchQuery || programFilter !== 'all' || sessionFilter !== 'all') && (
            <button
              onClick={() => {
                setSearchQuery('');
                setProgramFilter('all');
                setSessionFilter('all');
              }}
              className="col-span-2 sm:col-span-1 py-2 px-3 bg-rose-50 hover:bg-rose-100 text-rose-700 border border-rose-200 rounded-xl text-xs font-bold transition-colors flex items-center justify-center gap-1.5 cursor-pointer"
            >
              <RefreshCw className="w-3.5 h-3.5" />
              <span>{language === 'bn' ? 'রিসেট' : 'Reset'}</span>
            </button>
          )}
        </div>

        {/* Status Count and View Toggle Row */}
        <div className="flex items-center justify-between pt-2 border-t border-gray-100 text-xs">
          <span className="font-bold text-[#006a4e] flex items-center gap-1.5">
            <span className="w-2 h-2 rounded-full bg-emerald-500 animate-pulse" />
            {language === 'bn'
              ? `মোট প্রাপ্ত সদস্য: ${filteredMembers.length} জন`
              : `Found: ${filteredMembers.length} members`}
          </span>

          {/* View Mode Toggle Buttons */}
          <div className="flex items-center bg-gray-100 p-0.5 rounded-lg border border-gray-200">
            <button
              onClick={() => setViewMode('grid')}
              className={`px-2.5 py-1 rounded-md text-[11px] font-bold transition-all flex items-center gap-1 cursor-pointer ${
                viewMode === 'grid'
                  ? 'bg-white text-[#006a4e] shadow-2xs'
                  : 'text-gray-600 hover:text-gray-900'
              }`}
            >
              <LayoutGrid className="w-3.5 h-3.5" />
              <span>{language === 'bn' ? 'রঙিন কার্ড' : 'Cards'}</span>
            </button>
            <button
              onClick={() => setViewMode('table')}
              className={`px-2.5 py-1 rounded-md text-[11px] font-bold transition-all flex items-center gap-1 cursor-pointer ${
                viewMode === 'table'
                  ? 'bg-white text-[#006a4e] shadow-2xs'
                  : 'text-gray-600 hover:text-gray-900'
              }`}
            >
              <List className="w-3.5 h-3.5" />
              <span>{language === 'bn' ? 'তালিকা' : 'Table'}</span>
            </button>
          </div>
        </div>
      </div>

      {/* Members Directory Content */}
      <div id="members-directory-section" className="space-y-4 sm:space-y-6">
        {loading ? (
          <div className="py-16 text-center space-y-3 bg-white rounded-2xl border border-gray-200">
            <div className="w-10 h-10 border-4 border-[#006a4e] border-t-transparent rounded-full animate-spin mx-auto" />
            <p className="text-xs sm:text-sm font-bold text-gray-600">
              {language === 'bn' ? 'সদস্য তালিকা লোড হচ্ছে...' : 'Loading members directory...'}
            </p>
          </div>
        ) : filteredMembers.length === 0 ? (
          <div className="py-16 text-center bg-white border border-[#d2e4d2] rounded-2xl space-y-3 p-6 shadow-xs">
            <Users className="w-12 h-12 text-gray-300 mx-auto" />
            <h3 className="text-sm sm:text-base font-bold text-gray-700">
              {language === 'bn' ? 'কোনো সদস্যের তথ্য পাওয়া যায়নি' : 'No members found'}
            </h3>
            <p className="text-xs text-gray-500 max-w-md mx-auto">
              {language === 'bn'
                ? 'অনুগ্রহ করে সঠিক রেজিস্ট্রেশন ফরম নং বা শেষ ৪টি ডিজিট (যেমন: 4655) লিখে পুনরায় অনুসন্ধান করুন।'
                : 'Please search with a valid 4-digit registration number (e.g. 4655).'}
            </p>
          </div>
        ) : viewMode === 'grid' ? (
          /* Mobile-First Member Cards with Uniform Amber-Cream Theme */
          <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-4 sm:gap-5">
            {paginatedMembers.map((member, idx) => {
              const formNoStr = member.formNo || member.id;
              const last4 = formNoStr.slice(-4);
              const prefix = formNoStr.slice(0, -4);

              // Clean address display
              const displayAddress =
                member.currentAddress ||
                (member.village && member.district ? `${member.village}, ${member.district}` : member.district) ||
                'ময়মনসিংহ';

              return (
                <div
                  key={member.id || idx}
                  className="bg-[#fcfaf4] border-2 border-amber-400 rounded-2xl p-4 sm:p-5 shadow-sm hover:shadow-md transition-all flex flex-col justify-between space-y-3.5 relative overflow-hidden group"
                >
                  {/* Top Row: Green Dot + Form No. + Form No. Pill */}
                  <div className="flex items-center justify-between pb-2 border-b border-gray-200/80">
                    <div className="flex items-center gap-2">
                      <span className="w-2.5 h-2.5 rounded-full bg-[#006a4e] inline-block shrink-0" />
                      <span className="text-xs font-black text-gray-800">ফরম নং:</span>
                    </div>
                    <span className="font-mono text-xs font-bold bg-white px-2.5 py-1 rounded-xl border border-gray-200/90 shadow-2xs tracking-wide text-gray-800">
                      <span className="text-gray-700">{prefix}</span>
                      <span className="text-rose-600 font-black text-sm">{last4}</span>
                    </span>
                  </div>

                  {/* Card Profile Section: Photo + Name + Program */}
                  <div className="flex items-start gap-3.5">
                    {/* Warm Amber Rounded Avatar / Photo */}
                    <div className="w-14 h-14 sm:w-16 sm:h-16 rounded-2xl bg-[#d97706] border-2 border-amber-500 text-white flex items-center justify-center font-black overflow-hidden shrink-0 shadow-sm relative">
                      {member.userPhotoUrl ? (
                        <img
                          src={member.userPhotoUrl}
                          alt={member.applicantNameBn}
                          className="w-full h-full object-cover"
                        />
                      ) : (
                        <span className="text-2xl font-bold">
                          {member.applicantNameBn.charAt(0) || 'ম'}
                        </span>
                      )}
                      {/* Verified Checkmark Badge */}
                      <span className="absolute bottom-0.5 right-0.5 bg-white rounded-full p-0.5 shadow-xs border border-gray-100">
                        <CheckCircle2 className="w-3.5 h-3.5 text-emerald-600 fill-emerald-50" />
                      </span>
                    </div>

                    {/* Identity Information */}
                    <div className="flex-1 min-w-0 space-y-1.5 pt-0.5">
                      <h3 className="font-black text-gray-950 text-base sm:text-lg truncate leading-tight">
                        {member.applicantNameBn}
                      </h3>
                      <div>
                        <span className="inline-block bg-white text-gray-800 font-bold px-2.5 py-0.5 rounded-lg border border-gray-200 text-[11.5px] shadow-2xs">
                          {getProgramLabel(member.program)}
                        </span>
                      </div>
                    </div>
                  </div>

                  {/* White Info Box: Batch, Mobile, Address */}
                  <div className="bg-white p-3 sm:p-3.5 rounded-xl space-y-2.5 text-xs text-gray-800 border border-amber-200/60 shadow-2xs">
                    {/* ব্যাচ / সেশন */}
                    <div className="flex items-center justify-between gap-2">
                      <span className="text-gray-700 flex items-center gap-1.5 font-bold">
                        <GraduationCap className="w-4 h-4 text-emerald-700 shrink-0" />
                        <span>ব্যাচ/সেশন:</span>
                      </span>
                      <span className="font-bold text-[#166534] bg-[#dcfce7] px-2.5 py-0.5 rounded-lg text-xs border border-emerald-300 font-mono">
                        {member.session || '—'}
                      </span>
                    </div>

                    {/* মোবাইল নম্বর */}
                    <div className="flex items-center justify-between gap-2">
                      <span className="text-gray-700 flex items-center gap-1.5 font-bold">
                        <Phone className="w-4 h-4 text-blue-600 shrink-0" />
                        <span>মোবাইল:</span>
                      </span>
                      <a
                        href={member.mobile ? `tel:${member.mobile}` : undefined}
                        className="font-mono font-bold text-gray-900 hover:text-emerald-700 transition-colors bg-white px-2.5 py-0.5 rounded-lg border border-gray-200 shadow-2xs text-xs"
                      >
                        {member.mobile ? (member.mobile.startsWith('+88') ? member.mobile : `+88${member.mobile}`) : '—'}
                      </a>
                    </div>

                    {/* ঠিকানা */}
                    <div className="flex items-start justify-between gap-2 pt-0.5">
                      <span className="text-gray-700 flex items-center gap-1.5 font-bold shrink-0">
                        <MapPin className="w-4 h-4 text-rose-600 shrink-0" />
                        <span>ঠিকানা:</span>
                      </span>
                      <span className="font-semibold text-gray-800 text-right leading-tight line-clamp-2 max-w-[210px]">
                        {displayAddress}
                      </span>
                    </div>
                  </div>

                  {/* Bottom Burnt Amber Action Button */}
                  <button
                    onClick={() => setSelectedMember(member)}
                    className="w-full min-h-[42px] py-2.5 px-4 bg-[#a14006] hover:bg-[#8b3604] active:bg-[#732c02] text-white text-xs sm:text-sm font-bold rounded-xl shadow-md transition-all flex items-center justify-center gap-2 cursor-pointer active:scale-98"
                  >
                    <Eye className="w-4 h-4 text-amber-300" />
                    <span>{language === 'bn' ? 'সদস্য কার্ড ও বিস্তারিত' : 'View Full Slip'}</span>
                  </button>
                </div>
              );
            })}
          </div>
        ) : (
          /* Responsive Table View: Batch, Address, Phone */
          <div className="overflow-x-auto rounded-2xl border border-[#c1d3c1] shadow-xs bg-white">
            <table className="w-full text-left text-xs border-collapse min-w-[640px]">
              <thead>
                <tr className="bg-[#006a4e] text-white font-bold border-b border-emerald-700">
                  <th className="py-3 px-3">#</th>
                  <th className="py-3 px-3">{language === 'bn' ? 'রেজি. ফরম নং' : 'Form No.'}</th>
                  <th className="py-3 px-3">{language === 'bn' ? 'সদস্যের নাম ও কোর্স' : 'Name & Program'}</th>
                  <th className="py-3 px-3">{language === 'bn' ? 'ব্যাচ / সেশন' : 'Batch / Session'}</th>
                  <th className="py-3 px-3">{language === 'bn' ? 'ফোন নম্বর' : 'Phone'}</th>
                  <th className="py-3 px-3">{language === 'bn' ? 'ঠিকানা' : 'Address'}</th>
                  <th className="py-3 px-3 text-center">{language === 'bn' ? 'অ্যাকশন' : 'Action'}</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-gray-200">
                {paginatedMembers.map((member, idx) => {
                  const formNoStr = member.formNo || member.id;
                  const last4 = formNoStr.slice(-4);
                  const prefix = formNoStr.slice(0, -4);

                  const displayAddress =
                    member.currentAddress ||
                    (member.village && member.district ? `${member.village}, ${member.district}` : member.district) ||
                    '—';

                  return (
                    <tr
                      key={member.id || idx}
                      className="hover:bg-[#f3f9f4] transition-colors"
                    >
                      <td className="py-3 px-3 text-gray-500 font-mono font-bold">
                        {startIndex + idx + 1}
                      </td>
                      <td className="py-3 px-3">
                        <span className="font-mono text-xs font-black bg-emerald-50 px-2 py-0.5 rounded border border-emerald-200 whitespace-nowrap">
                          <span className="text-[#006a4e]">{prefix}</span>
                          <span className="text-rose-600 font-black">{last4}</span>
                        </span>
                      </td>
                      <td className="py-3 px-3">
                        <div className="flex items-center gap-2.5">
                          <div className="w-8 h-8 rounded-full bg-emerald-600 text-white flex items-center justify-center font-bold overflow-hidden shrink-0 shadow-2xs">
                            {member.userPhotoUrl ? (
                              <img
                                src={member.userPhotoUrl}
                                alt={member.applicantNameBn}
                                className="w-full h-full object-cover"
                              />
                            ) : (
                              <span>{member.applicantNameBn.charAt(0) || 'স'}</span>
                            )}
                          </div>
                          <div className="min-w-0">
                            <p className="font-extrabold text-gray-900 text-xs truncate">
                              {member.applicantNameBn}
                            </p>
                            <span className="text-[10px] text-[#006a4e] font-bold">
                              {getProgramLabel(member.program)}
                            </span>
                          </div>
                        </div>
                      </td>
                      <td className="py-3 px-3 font-semibold text-gray-900">
                        {member.session || '—'}
                      </td>
                      <td className="py-3 px-3 font-mono font-bold text-gray-900">
                        {member.mobile || '—'}
                      </td>
                      <td className="py-3 px-3 text-gray-700 max-w-[160px] truncate">
                        {displayAddress}
                      </td>
                      <td className="py-3 px-3 text-center">
                        <button
                          onClick={() => setSelectedMember(member)}
                          className="inline-flex items-center gap-1 px-2.5 py-1.5 bg-[#006a4e] hover:bg-[#00523d] text-white rounded-lg font-bold text-xs shadow-2xs transition-colors cursor-pointer"
                        >
                          <Eye className="w-3.5 h-3.5 text-amber-300" />
                          <span>{language === 'bn' ? 'দেখুন' : 'View'}</span>
                        </button>
                      </td>
                    </tr>
                  );
                })}
              </tbody>
            </table>
          </div>
        )}

        {/* Dynamic Pagination Bar (Max 9 members per page) */}
        {!loading && filteredMembers.length > 0 && totalPages > 1 && (
          <div className="bg-white border border-emerald-200/80 rounded-2xl p-3 sm:p-4 shadow-xs flex flex-col sm:flex-row items-center justify-between gap-3">
            {/* Range & Total Count info */}
            <div className="text-xs font-semibold text-gray-700 text-center sm:text-left">
              {language === 'bn' ? (
                <span>
                  মোট <strong className="text-[#006a4e] font-bold">{totalMembersCount}</strong> জন অনুমোদিত সদস্যের মধ্যে{' '}
                  <strong className="text-gray-900 font-bold">{startIndex + 1} - {endIndex}</strong> নম্বর প্রদর্শিত হচ্ছে{' '}
                  <span className="text-gray-500 font-normal">
                    (পৃষ্ঠা <strong className="text-[#006a4e]">{currentPage}</strong> / {totalPages})
                  </span>
                </span>
              ) : (
                <span>
                  Showing <strong className="text-gray-900 font-bold">{startIndex + 1} - {endIndex}</strong> of{' '}
                  <strong className="text-[#006a4e] font-bold">{totalMembersCount}</strong> approved members{' '}
                  <span className="text-gray-500 font-normal">
                    (Page <strong className="text-[#006a4e]">{currentPage}</strong> of {totalPages})
                  </span>
                </span>
              )}
            </div>

            {/* Navigation Buttons */}
            <div className="flex items-center gap-1.5 shrink-0">
              {/* Previous Page Button */}
              <button
                onClick={() => handlePageChange(currentPage - 1)}
                disabled={currentPage === 1}
                className={`inline-flex items-center gap-1 px-3 py-2 rounded-xl text-xs font-bold transition-all ${
                  currentPage === 1
                    ? 'bg-gray-100 text-gray-400 cursor-not-allowed border border-gray-200'
                    : 'bg-white hover:bg-emerald-50 text-[#006a4e] hover:text-[#004d38] border border-emerald-300 shadow-2xs cursor-pointer active:scale-95'
                }`}
                title={language === 'bn' ? 'পূর্ববর্তী পৃষ্ঠা' : 'Previous Page'}
              >
                <ChevronLeft className="w-4 h-4" />
                <span>{language === 'bn' ? 'পূর্ববর্তী' : 'Previous'}</span>
              </button>

              {/* Numbered Page Buttons */}
              <div className="flex items-center gap-1">
                {Array.from({ length: totalPages }, (_, i) => i + 1).map((pageNum) => {
                  const isActive = pageNum === currentPage;
                  return (
                    <button
                      key={pageNum}
                      onClick={() => handlePageChange(pageNum)}
                      className={`min-w-[34px] h-[34px] px-2 rounded-xl text-xs font-bold transition-all cursor-pointer flex items-center justify-center ${
                        isActive
                          ? 'bg-[#006a4e] text-white shadow-xs scale-105 ring-2 ring-emerald-300'
                          : 'bg-white hover:bg-gray-100 text-gray-700 border border-gray-200'
                      }`}
                    >
                      {pageNum}
                    </button>
                  );
                })}
              </div>

              {/* Next Page Button */}
              <button
                onClick={() => handlePageChange(currentPage + 1)}
                disabled={currentPage === totalPages}
                className={`inline-flex items-center gap-1 px-3.5 py-2 rounded-xl text-xs font-bold transition-all ${
                  currentPage === totalPages
                    ? 'bg-gray-100 text-gray-400 cursor-not-allowed border border-gray-200'
                    : 'bg-[#006a4e] hover:bg-[#00523d] text-white shadow-xs cursor-pointer active:scale-95 ring-1 ring-emerald-700'
                }`}
                title={language === 'bn' ? 'পরবর্তী পৃষ্ঠা' : 'Next Page'}
              >
                <span>{language === 'bn' ? 'পরবর্তী' : 'Next'}</span>
                <ChevronRight className="w-4 h-4" />
              </button>
            </div>
          </div>
        )}
      </div>

      {/* Member Details Modal / ID Card Slip */}
      {selectedMember && (
        <MemberCardModal
          member={selectedMember}
          language={language}
          onClose={() => setSelectedMember(null)}
        />
      )}
    </div>
  );
};
